---

- name: Include menu tasks for platforms
  when:
    - os.state is defined
    - os.state == "present"
    - os.platforms is defined
    - os.platforms is iterable
    - os.platforms | length > 0
    - pxe_sysprep_specs_platforms[platform.name] is defined
    - pxe_sysprep_specs_platforms[platform.name].state == "present"
    - platform.name in menu_platforms_list
    - platform.state is defined
    - platform.state == "present"
  loop: "{{ os.platforms | flatten }}"
  loop_control:
    loop_var: platform
    label: "platform: {{ platform.name }}"
  ansible.builtin.debug:
    msg: "generate menu {{ server.name }} {{ os_images_list }} {{ platform.name }} {{ platform.partitionings }}"
  # ansible.builtin.template:
  #   src: "templates/menu/{{ platform.name }}/menu.cfg.i2"
  #   dest: "{{ pxe_sysprep_specs_platforms[platform.name].menu_folder }}/{{ server.name }}.cfg"
  #   owner: root
  #   group: root
  #   mode: "0644"
  #   variable_start_string: "((%%"
  #   variable_end_string: "%%))"
