---

- name: Define menu os images list
  block:
    - name: Define menu os images list
      ansible.builtin.set_fact:
        os_images_list: []
  
    - name: Define menu os images list
      when:
        - server.state is defined
        - server.state == "present"
        - server.os_images_list is defined
        - server.os_images_list is iterable
        - server.os_images_list | length > 0
        - os.state is defined
        - os.state == "present"
        - pxe_sysprep_specs_os_images[os.name] is defined
        - pxe_sysprep_specs_os_images[os.name].state == "present"
      loop: "{{ server.os_images_list | flatten }}"
      loop_control:
        loop_var: os
        label: "os: {{ os.name }}"
      ansible.builtin.set_fact:
        os_images_list: '{{ os_images_list + [os.name] }}'

    # - name: Define menu os images list
    #   ansible.builtin.debug:
    #     var: os_images_list



- name: Include menu tasks for os images
  ansible.builtin.include_tasks:
    file: "sub-tasks/sub_generate_menu_os.yml"
  # vars:


# - name: Define menu os images list
#   block:
#     - name: Define menu os images list
#       ansible.builtin.set_fact:
#         os_images_list: []
#     - name: Define menu os images list
#       when:
#         - server.state is defined
#         - server.state == "present"
#         - server.os_images_list is defined
#         - server.os_images_list is iterable
#         - server.os_images_list | length > 0
#         - os.state is defined
#         - os.state == "present"
#       loop: "{{ server.os_images_list | flatten }}"
#       loop_control:
#         loop_var: os
#         label: "os: {{ os.name }}"
#       ansible.builtin.set_fact:
#         os_images_list: '{{ os_images_list + [os.name] }}'










# - name: Include menu tasks for platforms
#   # when:
#   #   - os.state is defined
#   #   - os.state == "present"
#   #   - os.platforms is defined
#   #   - os.platforms is iterable
#   #   - os.platforms | length > 0
#   #   - pxe_sysprep_specs_platforms[platform.name] is defined 
#   loop: "{{ platforms_list | flatten }}"
#   loop_control:
#     loop_var: platform
#     label: "platform: {{ platform }}"
#   ansible.builtin.include_tasks:
#     file: "sub-tasks/sub_generate_menu_platform.yml"





# - name: Include menu tasks for...
#   loop: "{{ os_images_list | flatten }}"
#   loop_control:
#     loop_var: os
#     label: "os: {{ os }}"
#   ansible.builtin.debug:
#     msg: "os {{ os }}"
  # ansible.builtin.include_tasks:
  #   file: "sub-tasks/sub_generate_menu_.yml"







# - name: Include menu tasks for os images
#   ansible.builtin.set_fact:
#     os_images_list: "{{ server.os_images_list | map(attribute='name') | list }}"


# - name: Include menu tasks for os images
#   ansible.builtin.debug:
#     var: os_images_list
