---

- name: Include sysprep tasks for server/os/bootmode
  when:
    - os.state is defined
    - os.state == "present"
    - os.bootmodes is defined
    - os.bootmodes is iterable
    - os.bootmodes | length > 0
    - pxe_sysprep_specs_bootmodes[bootmode.name] is defined
    - pxe_sysprep_specs_bootmodes[bootmode.name].state == "present"
  loop: "{{ os.bootmodes | flatten }}"
  loop_control:
    loop_var: bootmode
    label: "bootmode: {{ bootmode.name }}"
  ansible.builtin.include_tasks:
    file: "sub-tasks/sub_generate_sysprep_server_os_bootmode.yml"
