---

- name: "Include tasks for sysprep [server: {{ server.name }}, os: {{ os.name }}, bootmode: {{ bootmode.name }}, partitioning: {{ partitioning }}]"
  when:
    - partitioning is defined
    - partitioning is iterable
    - partitioning | length > 0
    - pxe_sysprep_specs_bootmodes[bootmode.name] is defined
    - pxe_sysprep_specs_os_images[os.name]['bootmodes'][bootmode.name] is defined
    - pxe_sysprep_specs_os_images[os.name]['bootmodes'][bootmode.name]['partitionings'] is defined
    - pxe_sysprep_specs_os_images[os.name]['bootmodes'][bootmode.name]['partitionings'][partitioning] is defined
    - pxe_sysprep_specs_os_images[os.name]['bootmodes'][bootmode.name]['partitionings'][partitioning].state == "present"
  loop: "{{ bootmode.partitionings | flatten }}"
  loop_control:
    loop_var: partitioning
    label: "partitioning: {{ partitioning }}"
  ansible.builtin.include_tasks:
    file: "sub-tasks/sub_generate_sysprep_server_os_bootmode_partitioning.yml"


- name: "Include tasks for sysprep [server: {{ server.name }}, os: {{ os.name }}, bootmode: {{ bootmode.name }}]"
  when:
    - bootmode.partitionings is not defined
  block:
    - name: Define menu sysprep file url
      ansible.builtin.set_fact:
        menu_sysprep_file_url: >-
          {{ pxe_sysprep_specs_bootmodes[bootmode.name].pxe_http_addr }}/{{ pxe_sysprep_specs_bootmodes[bootmode.name].sysprep_folder }}/{{ server.name }}_{{ os.name }}.cfg


    - name: Define menu entry append options
      ansible.builtin.set_fact:
        menu_append_opts: >-
          {{ pxe_sysprep_specs_os_images[os.name]['bootmodes'][bootmode.name]['menu'].append_opts }}
    - name: Define menu entry append options
      when:
        - pxe_sysprep_specs_os_images[os.name]['bootmodes'][bootmode.name]['menu'].append_sysprep_server_opts is defined
      ansible.builtin.set_fact:
        menu_append_opts: >-
          {{ menu_append_opts }}
          {{ pxe_sysprep_specs_os_images[os.name]['bootmodes'][bootmode.name]['menu'].append_sysprep_server_opts }}
    - name: Define menu entry append options
      ansible.builtin.set_fact:
        menu_append_opts: "{{ menu_append_opts | regex_replace('VAR_SERVER_SYSPREP_FILE', menu_sysprep_file_url) }}"
    - name: Define menu entry append options
      ansible.builtin.set_fact:
        menu_append_opts: "{{ menu_append_opts | regex_replace('VAR_SERVER_NAME', server.name) }}"
    - name: Define menu entry append options
      ansible.builtin.set_fact:
        menu_append_opts: "{{ menu_append_opts | regex_replace('VAR_SERVER_DOMAIN', server.domain) }}"
    - name: Define menu entry append options
      ansible.builtin.set_fact:
        menu_append_opts: "{{ menu_append_opts | regex_replace('VAR_PXE_HTTP_URL', pxe_sysprep_specs_bootmodes[bootmode.name].pxe_http_addr) }}"


    - name: Add menu entry list
      ansible.builtin.set_fact:
        menu_entries: '{{ menu_entries + [ { "bootmode" : bootmode.name, "os" : os.name, "menu_append_opts" : menu_append_opts } ] }}'


    - name: Generate sysprep file
      when:
        - pxe_sysprep_specs_os_images[os.name].type == "sysprep"
      ansible.builtin.debug:
        msg: "generate sysprep {{ server.name }} {{ os.name }} {{ bootmode.name }}"
