---

- name: Generate pxe
  when:
    - pxe_deploy_configure_action == "generate"
  block:
    - name: Set server list
      when:
        - pxe_sysprep_generate_servers_list is defined
        - pxe_sysprep_generate_servers_list is iterable
        - pxe_sysprep_generate_servers_limit_list is not defined or pxe_sysprep_generate_servers_limit_list | length == 0
      ansible.builtin.set_fact:
        pxe_sysprep_generate_servers_list2: "{{ pxe_sysprep_generate_servers_list }}"


    - name: Set new server with selected list
      when:
        - pxe_sysprep_generate_servers_list is defined
        - pxe_sysprep_generate_servers_list is iterable
        - pxe_sysprep_generate_servers_limit_list is defined
        - pxe_sysprep_generate_servers_limit_list | length > 0
      block:
        - name: Set new (empty) server list with selected list
          ansible.builtin.set_fact:
            pxe_sysprep_generate_servers_list2: []
        - name: Set new server list with selected list
          when:
            - server.name in pxe_sysprep_generate_servers_limit_list
          loop: "{{ pxe_sysprep_generate_servers_list | flatten }}"
          loop_control:
            loop_var: server
            label: "server: {{ server.name }}"
          ansible.builtin.set_fact:
            pxe_sysprep_generate_servers_list2: "{{ pxe_sysprep_generate_servers_list2 + [server] }}"


    - name: Include tasks for install defaults menu files
      when:
        - pxe_sysprep_specs_bootmodes[bootmode].state == "present"
      loop: "{{ pxe_sysprep_specs_bootmodes | flatten }}"
      loop_control:
        loop_var: bootmode
        label: "bootmode: {{ bootmode }}"
      ansible.builtin.include_tasks:
        file: "sub-tasks/sub_install_bootmodes_menu_files.yml"

    - name: "Include tasks for sysprep [server: {{ server.name }}]"
      when:
        - server.state is defined
        - server.state == "present"
      loop: "{{ pxe_sysprep_generate_servers_list2 | flatten }}"
      loop_control:
        loop_var: server
        label: "server: {{ server.name }}"
      ansible.builtin.include_tasks:
        file: "sub-tasks/sub_generate_sysprep_server.yml"


- name: Cleanup pxe
  when:
    - pxe_deploy_configure_action == "cleanup"
  block:
    - name: Include tasks for cleanup menu files
      when:
        - pxe_sysprep_specs_bootmodes[bootmode].state == "present"
      loop: "{{ pxe_sysprep_specs_bootmodes | flatten }}"
      loop_control:
        loop_var: bootmode
        label: "bootmode: {{ bootmode }}"
      ansible.builtin.include_tasks:
        file: "sub-tasks/sub_cleanup_menu_files.yml"

    - name: Include  tasks for cleanup sysprep files
      loop: "{{ pxe_sysprep_specs_bootmodes | flatten }}"
      loop_control:
        loop_var: bootmode
        label: "bootmode: {{ bootmode }}"
      ansible.builtin.include_tasks:
        file: "sub-tasks/sub_cleanup_sysprep_files.yml"
