---
# - name: Prepare pxe server
#   when:
#     - pxe_deploy_configure_action == "generate"
#   block:
#     - name: Copy default pxe menu bios files
#       loop: "{{ pxe_deploy_menu_default_files_bios | flatten }}"
#       ansible.builtin.copy:
#         src: "menu/bios/{{ item }}"
#         dest: "{{ pxe_deploy_menu_folder }}/bios/"
#         mode: "0644"
#         owner: root
#         group: root
#     - name: Copy default pxe menu efi64 files
#       loop: "{{ pxe_deploy_menu_default_files_efi64 | flatten }}"
#       ansible.builtin.copy:
#         src: "menu/efi64/{{ item }}"
#         dest: "{{ pxe_deploy_menu_folder }}/efi64/"
#         mode: "0644"
#         owner: root
#         group: root


- name: Generate pxe
  when:
    - pxe_deploy_configure_action == "generate"
  block:
    - name: Include sysprep tasks for servers
      when:
        - server.state is defined
        - server.state == "present"
      loop: "{{ pxe_sysprep_generate_servers_list | flatten }}"
      loop_control:
        loop_var: server
        label: "server: {{ server.name }}"
      ansible.builtin.include_tasks:
        file: "sub-tasks/sub_generate_sysprep_server.yml"


    # - name: Prepare menu entries list
    #   ansible.builtin.debug:
    #     var: menu_entries



    # - name: Define menu platforms list
    #   block:
    #     - name: Define menu platforms list
    #       ansible.builtin.set_fact:
    #         menu_platforms_list: []
    #     - name: Define menu platforms list
    #       when:
    #         - pxe_sysprep_specs_platforms[platform].state == "present"
    #       loop: "{{ pxe_sysprep_specs_platforms | flatten }}"
    #       loop_control:
    #         loop_var: platform
    #         label: "platform: {{ platform }}"
    #       ansible.builtin.set_fact:
    #         menu_platforms_list: '{{ menu_platforms_list + [platform] }}'
    #     # - name: Define menu platforms list
    #     #   ansible.builtin.debug:
    #     #     var: menu_platforms_list


    # - name: Include menu tasks for servers
    #   when:
    #     - server.state is defined
    #     - server.state == "present"
    #   loop: "{{ pxe_sysprep_generate_servers_list | flatten }}"
    #   loop_control:
    #     loop_var: server
    #     label: "server: {{ server.name }}"
    #   ansible.builtin.include_tasks:
    #     file: "sub-tasks/sub_generate_menu_server.yml"


# - name: Cleanup pxe
#   when:
#     - pxe_deploy_configure_action == "cleanup"
#   block:
#     - name: Identify old menu for cleanup
#       register: menu_files_to_delete
#       ansible.builtin.find:
#         paths: "{{ pxe_deploy_menu_folder }}"
#         patterns: "*.cfg"
#         recurse: true
#         file_type: file

#     - name: Old menu cleanup
#       when:
#         - menu_files_to_delete.files is defined
#         - menu_files_to_delete.files is iterable
#       loop: "{{ menu_files_to_delete.files | flatten }}"
#       loop_control:
#         loop_var: file
#         label: "file: {{ file.path }}"
#       ansible.builtin.file:
#         path: "{{ file.path }}"
#         state: absent

#     - name: Identify old sysprep for cleanup
#       register: sysprep_files_to_delete
#       ansible.builtin.find:
#         paths: "{{ pxe_deploy_sysprep_folder }}"
#         patterns: "*.cfg"
#         recurse: true

#     - name: Old sysprep cleanup
#       when:
#         - sysprep_files_to_delete.files is defined
#         - sysprep_files_to_delete.files is iterable
#       loop: "{{ sysprep_files_to_delete.files | flatten }}"
#       loop_control:
#         loop_var: file
#         label: "file: {{ file.path }}"
#       ansible.builtin.file:
#         path: "{{ file.path }}"
#         state: absent
