---
- name: Generate pxe
  when:
    - pxe_deploy_configure_action == "generate"
  block:
    - name: Copy default pxe menu bios files
      loop: "{{ pxe_deploy_menu_default_files_bios | flatten }}"
      ansible.builtin.copy:
        src: "menu/bios/{{ item }}"
        dest: "{{ pxe_deploy_menu_folder }}/bios/"
        mode: "0644"
        owner: root
        group: root

    - name: Create pxe menu bios
      loop: "{{ pxe_deploy | flatten }}"
      loop_control:
        loop_var: server
        label: "server: {{ server.name }}, os: {{ server.os }}"
      ansible.builtin.template:
        src: "menu/bios/menu.cfg.j2"
        dest: "{{ pxe_deploy_menu_folder }}/bios/{{ server.name }}.cfg"
        mode: "0644"
        owner: root
        group: root

    - name: Create pxe sysprep bios
      loop: "{{ pxe_deploy | flatten }}"
      loop_control:
        loop_var: server
        label: "server: {{ server.name }}, os: {{ server.os }}"
      ansible.builtin.template:
        src: "sysprep/bios/sysprep-{{ server.os }}.cfg.j2"
        dest: "{{ pxe_deploy_sysprep_folder }}/bios/{{ server.name }}.cfg"
        mode: "0644"
        owner: root
        group: root

    - name: Copy default pxe menu efi64 files
      loop: "{{ pxe_deploy_menu_default_files_efi64 | flatten }}"
      ansible.builtin.copy:
        src: "menu/efi64/{{ item }}"
        dest: "{{ pxe_deploy_menu_folder }}/efi64/"
        mode: "0644"
        owner: root
        group: root

    - name: Create pxe menu efi64
      loop: "{{ pxe_deploy | flatten }}"
      loop_control:
        loop_var: server
        label: "server: {{ server.name }}, os: {{ server.os }}"
      ansible.builtin.template:
        src: "menu/efi64/menu.cfg.j2"
        dest: "{{ pxe_deploy_menu_folder }}/efi64/{{ server.name }}.cfg"
        mode: "0644"
        owner: root
        group: root

    - name: Create pxe sysprep efi64
      loop: "{{ pxe_deploy | flatten }}"
      loop_control:
        loop_var: server
        label: "server: {{ server.name }}, os: {{ server.os }}"
      ansible.builtin.template:
        src: "sysprep/efi64/sysprep-{{ server.os }}.cfg.j2"
        dest: "{{ pxe_deploy_sysprep_folder }}/efi64/{{ server.name }}.cfg"
        mode: "0644"
        owner: root
        group: root


- name: Cleanup pxe
  when:
    - pxe_deploy_configure_action == "cleanup"
  block:
    # - name: create pxe menu directory structure
    #   ansible.builtin.file:
    #     path: "{{ pxe_deploy_menu_folder }}/{{ item }}"
    #     state: directory
    #     mode: 0777
    #     owner: root
    #     group: root
    #   loop:
    #     - bios
    #     - efi64

    # - name: create pxe sysprep directory structure
    #   ansible.builtin.file:
    #     path: "{{ pxe_deploy_sysprep_folder }}/{{ item }}"
    #     state: directory
    #     mode: 0777
    #     owner: root
    #     group: root
    #   loop:
    #     - bios
    #     - efi64

    - name: Identify old menu for cleanup
      register: menu_files_to_delete
      ansible.builtin.find:
        paths: "{{ pxe_deploy_menu_folder }}"
        patterns: "*.cfg"
        recurse: true
        file_type: file

    - name: Old menu cleanup
      when:
        - menu_files_to_delete.files is defined
        - menu_files_to_delete.files is iterable
      loop: "{{ menu_files_to_delete.files | flatten }}"
      loop_control:
        loop_var: file
        label: "file: {{ file.path }}"
      ansible.builtin.file:
        path: "{{ file.path }}"
        state: absent

    - name: Identify old sysprep for cleanup
      register: sysprep_files_to_delete
      ansible.builtin.find:
        paths: "{{ pxe_deploy_sysprep_folder }}"
        patterns: "*.cfg"
        recurse: true

    - name: Old sysprep cleanup
      when:
        - sysprep_files_to_delete.files is defined
        - sysprep_files_to_delete.files is iterable
      loop: "{{ sysprep_files_to_delete.files | flatten }}"
      loop_control:
        loop_var: file
        label: "file: {{ file.path }}"
      ansible.builtin.file:
        path: "{{ file.path }}"
        state: absent
