---

- name: Generate pxe
  when:
    - pxe_deploy_configure_action == "generate"
  block:
    - name: Include prepare tasks for defaults menu files
      when:
        - pxe_sysprep_specs_platforms[platform].state == "present"
      loop: "{{ pxe_sysprep_specs_platforms | flatten }}"
      loop_control:
        loop_var: platform
        label: "platform: {{ platform }}"
      ansible.builtin.include_tasks:
        file: "sub-tasks/sub_install_platforms_menu_files.yml"

    - name: Include sysprep tasks for servers
      when:
        - server.state is defined
        - server.state == "present"
      loop: "{{ pxe_sysprep_generate_servers_list | flatten }}"
      loop_control:
        loop_var: server
        label: "server: {{ server.name }}"
      ansible.builtin.include_tasks:
        file: "sub-tasks/sub_generate_sysprep_server.yml"


- name: Cleanup pxe
  when:
    - pxe_deploy_configure_action == "cleanup"
  block:
    - name: Include cleanup tasks for menu files
      when:
        - pxe_sysprep_specs_platforms[platform].state == "present"
      loop: "{{ pxe_sysprep_specs_platforms | flatten }}"
      loop_control:
        loop_var: platform
        label: "platform: {{ platform }}"
      ansible.builtin.include_tasks:
        file: "sub-tasks/sub_cleanup_menu_files.yml"

    - name: Include cleanup tasks for sysprep files
      loop: "{{ pxe_sysprep_specs_platforms | flatten }}"
      loop_control:
        loop_var: platform
        label: "platform: {{ platform }}"
      ansible.builtin.include_tasks:
        file: "sub-tasks/sub_cleanup_sysprep_files.yml"
