---
- name: generate pxe
  when: pxe_deploy_configure_action == "generate"
  block:
    - name: copy default pxe menu bios files
      loop:
        - default
        - default.entries
        - default.theme
        - splash.png
      ansible.builtin.copy:
        src: "menu/bios/{{ item }}"
        dest: "{{ pxe_deploy_menu_folder }}/bios/"
        mode: "0777"
        owner: root
        group: root

    - name: "create pxe menu bios"
      loop: "{{ pxe_deploy | flatten }}"
      loop_control:
        loop_var: server
      ansible.builtin.template:
        src: "menu/bios/menu.cfg.j2"
        dest: "{{ pxe_deploy_menu_folder }}/bios/{{ server.name }}.cfg"
        mode: "0777"
        owner: root
        group: root

    - name: "create pxe sysprep bios"
      loop: "{{ pxe_deploy | flatten }}"
      loop_control:
        loop_var: server
      ansible.builtin.template:
        src: "sysprep/bios/sysprep-{{ server.os }}.cfg.j2"
        dest: "{{ pxe_deploy_sysprep_folder }}/bios/{{ server.name }}.cfg"
        mode: "0777"
        owner: root
        group: root

    - name: copy default pxe menu efi64 files
      loop:
        - default
        - default.entries
        - default.theme
        - splash.png
      ansible.builtin.copy:
        src: "menu/efi64/{{ item }}"
        dest: "{{ pxe_deploy_menu_folder }}/efi64/"
        mode: "0777"
        owner: root
        group: root

    - name: "create pxe menu efi64"
      loop: "{{ pxe_deploy | flatten }}"
      loop_control:
        loop_var: server
      ansible.builtin.template:
        src: "menu/efi64/menu.cfg.j2"
        dest: "{{ pxe_deploy_menu_folder }}/efi64/{{ server.name }}.cfg"
        mode: "0777"
        owner: root
        group: root

    - name: "create pxe sysprep efi64"
      loop: "{{ pxe_deploy | flatten }}"
      loop_control:
        loop_var: server
      ansible.builtin.template:
        src: "sysprep/efi64/sysprep-{{ server.os }}.cfg.j2"
        dest: "{{ pxe_deploy_sysprep_folder }}/efi64/{{ server.name }}.cfg"
        mode: "0777"
        owner: root
        group: root


- name: cleanup pxe
  when: pxe_deploy_configure_action == "cleanup"
  block:
    # - name: create pxe menu directory structure
    #   ansible.builtin.file:
    #     path: "{{ pxe_deploy_menu_folder }}/{{ item }}"
    #     state: directory
    #     mode: 0777
    #     owner: root
    #     group: root
    #   loop:
    #     - bios
    #     - efi64

    # - name: create pxe sysprep directory structure
    #   ansible.builtin.file:
    #     path: "{{ pxe_deploy_sysprep_folder }}/{{ item }}"
    #     state: directory
    #     mode: 0777
    #     owner: root
    #     group: root
    #   loop:
    #     - bios
    #     - efi64

    - name: identify old menu for cleanup
      register: menu_files_to_delete
      ansible.builtin.find:
        paths: "{{ pxe_deploy_menu_folder }}"
        patterns: "*.cfg"
        recurse: true

    - name: old menu cleanup
      with_items: "{{ menu_files_to_delete.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent

    - name: identify old sysprep for cleanup
      register: sysprep_files_to_delete
      ansible.builtin.find:
        paths: "{{ pxe_deploy_sysprep_folder }}"
        patterns: "*.cfg"
        recurse: true

    - name: old sysprep cleanup
      with_items: "{{ sysprep_files_to_delete.files }}"
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
